steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/button', '.']
- name: 'gcr.io/cloudshell-images/custom-image-validation'
  args: ['image_test.py', '--image', 'gcr.io/$PROJECT_ID/button']
- name: 'gcr.io/cloud-builders/docker'
  args: ["-it", 'gcr.io/$PROJECT_ID/button', "/bin/bash"]
timeout: '1200s'
