import re
from pygments import lexer, token


class RedisLexer(lexer.RegexLexer):
    """
    Lexer for `Redis <https://redis.io/>`_ commands.

    ideas from:
    https://github.com/realpython/pygments-redis/blob/master/pygments_redis/redis.py

    Redis all commands:
    https://redis.io/commands
    """

    name = "Redis"
    aliases = ["redis"]
    flags = re.MULTILINE | re.UNICODE | re.IGNORECASE

    tokens = {
        "root": [
            (
                lexer.words(
                    (
                        r"APPEND",
                        r"AUTH",
                        r"BGREWRITEAOF",
                        r"BGSAVE",
                        r"BITCOUNT",
                        r"BITFIELD",
                        r"BITOP",
                        r"BITPOS",
                        r"BLPOP",
                        r"BRPOP",
                        r"BRPOPLPUSH",
                        r"BZPOPMIN",
                        r"BZPOPMAX",
                        r"CLIENT ID",
                        r"CLIENT KILL",
                        r"CLIENT LIST",
                        r"CLIENT GETNAME",
                        r"CLIENT PAUSE",
                        r"CLIENT REPLY",
                        r"CLIENT SETNAME",
                        r"CLIENT UNBLOCK",
                        r"CLUSTER ADDSLOTS",
                        r"CLUSTER COUNT-FAILURE-REPORTS",
                        r"CLUSTER COUNTKEYSINSLOT",
                        r"CLUSTER DELSLOTS",
                        r"CLUSTER FAILOVER",
                        r"CLUSTER FORGET",
                        r"CLUSTER GETKEYSINSLOT",
                        r"CLUSTER INFO",
                        r"CLUSTER KEYSLOT",
                        r"CLUSTER MEET",
                        r"CLUSTER NODES",
                        r"CLUSTER REPLICATE",
                        r"CLUSTER RESET",
                        r"CLUSTER SAVECONFIG",
                        r"CLUSTER SET-CONFIG-EPOCH",
                        r"CLUSTER SETSLOT",
                        r"CLUSTER SLAVES",
                        r"CLUSTER REPLICAS",
                        r"CLUSTER SLOTS",
                        r"COMMAND",
                        r"COMMAND COUNT",
                        r"COMMAND GETKEYS",
                        r"COMMAND INFO",
                        r"CONFIG GET",
                        r"CONFIG REWRITE",
                        r"CONFIG SET",
                        r"CONFIG RESETSTAT",
                        r"DBSIZE",
                        r"DEBUG OBJECT",
                        r"DEBUG SEGFAULT",
                        r"DECR",
                        r"DECRBY",
                        r"DEL",
                        r"DISCARD",
                        r"DUMP",
                        r"ECHO",
                        r"EVAL",
                        r"EVALSHA",
                        r"EXEC",
                        r"EXISTS",
                        r"EXPIRE",
                        r"EXPIREAT",
                        r"FLUSHALL",
                        r"FLUSHDB",
                        r"GEOADD",
                        r"GEOHASH",
                        r"GEOPOS",
                        r"GEODIST",
                        r"GEORADIUS",
                        r"GEORADIUSBYMEMBER",
                        r"GET",
                        r"GETBIT",
                        r"GETRANGE",
                        r"GETSET",
                        r"HDEL",
                        r"HEXISTS",
                        r"HGET",
                        r"HGETALL",
                        r"HINCRBY",
                        r"HINCRBYFLOAT",
                        r"HKEYS",
                        r"HLEN",
                        r"HMGET",
                        r"HMSET",
                        r"HSET",
                        r"HSETNX",
                        r"HSTRLEN",
                        r"HVALS",
                        r"INCR",
                        r"INCRBY",
                        r"INCRBYFLOAT",
                        r"INFO",
                        r"KEYS",
                        r"LASTSAVE",
                        r"LINDEX",
                        r"LINSERT",
                        r"LLEN",
                        r"LPOP",
                        r"LPUSH",
                        r"LPUSHX",
                        r"LRANGE",
                        r"LREM",
                        r"LSET",
                        r"LTRIM",
                        r"MEMORY DOCTOR",
                        r"MEMORY HELP",
                        r"MEMORY MALLOC-STATS",
                        r"MEMORY PURGE",
                        r"MEMORY STATS",
                        r"MEMORY USAGE",
                        r"MGET",
                        r"MIGRATE",
                        r"MONITOR",
                        r"MOVE",
                        r"MSET",
                        r"MSETNX",
                        r"MULTI",
                        r"OBJECT",
                        r"PERSIST",
                        r"PEXPIRE",
                        r"PEXPIREAT",
                        r"PFADD",
                        r"PFCOUNT",
                        r"PFMERGE",
                        r"PING",
                        r"PSETEX",
                        r"PSUBSCRIBE",
                        r"PUBSUB",
                        r"PTTL",
                        r"PUBLISH",
                        r"PUNSUBSCRIBE",
                        r"QUIT",
                        r"RANDOMKEY",
                        r"READONLY",
                        r"READWRITE",
                        r"RENAME",
                        r"RENAMENX",
                        r"RESTORE",
                        r"ROLE",
                        r"RPOP",
                        r"RPOPLPUSH",
                        r"RPUSH",
                        r"RPUSHX",
                        r"SADD",
                        r"SAVE",
                        r"SCARD",
                        r"SCRIPT DEBUG",
                        r"SCRIPT EXISTS",
                        r"SCRIPT FLUSH",
                        r"SCRIPT KILL",
                        r"SCRIPT LOAD",
                        r"SDIFF",
                        r"SDIFFSTORE",
                        r"SELECT",
                        r"SET",
                        r"SETBIT",
                        r"SETEX",
                        r"SETNX",
                        r"SETRANGE",
                        r"SHUTDOWN",
                        r"SINTER",
                        r"SINTERSTORE",
                        r"SISMEMBER",
                        r"SLAVEOF",
                        r"REPLICAOF",
                        r"SLOWLOG",
                        r"SMEMBERS",
                        r"SMOVE",
                        r"SORT",
                        r"SPOP",
                        r"SRANDMEMBER",
                        r"SREM",
                        r"STRLEN",
                        r"SUBSCRIBE",
                        r"SUNION",
                        r"SUNIONSTORE",
                        r"SWAPDB",
                        r"SYNC",
                        r"TIME",
                        r"TOUCH",
                        r"TTL",
                        r"TYPE",
                        r"UNSUBSCRIBE",
                        r"UNLINK",
                        r"UNWATCH",
                        r"WAIT",
                        r"WATCH",
                        r"ZADD",
                        r"ZCARD",
                        r"ZCOUNT",
                        r"ZINCRBY",
                        r"ZINTERSTORE",
                        r"ZLEXCOUNT",
                        r"ZPOPMAX",
                        r"ZPOPMIN",
                        r"ZRANGE",
                        r"ZRANGEBYLEX",
                        r"ZREVRANGEBYLEX",
                        r"ZRANGEBYSCORE",
                        r"ZRANK",
                        r"ZREM",
                        r"ZREMRANGEBYLEX",
                        r"ZREMRANGEBYRANK",
                        r"ZREMRANGEBYSCORE",
                        r"ZREVRANGE",
                        r"ZREVRANGEBYSCORE",
                        r"ZREVRANK",
                        r"ZSCORE",
                        r"ZUNIONSTORE",
                        r"SCAN",
                        r"SSCAN",
                        r"HSCAN",
                        r"ZSCAN",
                        r"XINFO",
                        r"XADD",
                        r"XTRIM",
                        r"XDEL",
                        r"XRANGE",
                        r"XREVRANGE",
                        r"XLEN",
                        r"XREAD",
                        r"XGROUP",
                        r"XREADGROUP",
                        r"XACK",
                        r"XCLAIM",
                        r"XPENDING",
                    ),
                    prefix=r"(?<=> )",
                ),
                token.Keyword,
            )
        ]
    }
