name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-24.04

    # FIXME
    # help test shouldn't depends on this to run
    services:
      redis:
        image: redis:5
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          architecture: 'x64'
      - name: Cache venv
        uses: actions/cache@v5
        with:
          path: venv
          # Look to see if there is a cache hit for the corresponding requirements file
          key: release-${{ runner.os }}-3.14-poetry-2.4.1-${{ hashFiles('poetry.lock') }}
      - name: Install Dependencies
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install poetry==2.4.1
          poetry check --lock
          poetry install
          python -c "import sys; print(sys.version)"
          pip list
      - name: Poetry Build
        run: |
          . venv/bin/activate
          poetry build
      - name: Test Build
        run: |
          python3 -m venv fresh_env
          . fresh_env/bin/activate
          pip install dist/*.whl

          iredis -h
          echo 'HELP GET' | iredis --raw | grep -F 'Get the value of'
          test "$(echo PING | iredis --raw)" = PONG

      - name: Upload to Pypi
        env:
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          . venv/bin/activate
          poetry publish --username __token__ --password "$PASSWORD"
